name: just_pdf_viewer_example
description: Demonstrates how to use the just_pdf_viewer package
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  just_pdf_viewer:
    path: ../
  http: ^1.1.0
  window_manager: ^0.3.9
  path_provider: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/sample.pdf
    - assets/sample_big.pdf